name: backdrop-federated 
channels:
  - conda-forge
  - defaults
dependencies:
  - jax=0.3.25
  - jupyter=1.0.0
  - ml_dtypes=0.2.0
  - notebook=7.0.8
  - numpy=1.26.4
  - pip=23.3.1
  - pycapnp=1.3.0
  - python=3.9.18
  - pytorch=2.2.0
  - syft=0.105.1 